sudo: required
services:
  - docker

before_install:
  - docker build -t benniskhalil/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true benniskhalil/react-test npm run test

after_success:
  - docker build -t benniskhalil/multi-client ./client
  - docker build -t benniskhalil/multi-nginx ./nginx
  - docker build -t benniskhalil/multi-server ./server
  - docker build -t benniskhalil/multi-worker ./worker
  # login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push benniskhalil/multi-client
  - docker push benniskhalil/multi-nginx
  - docker push benniskhalil/multi-server
  - docker push benniskhalil/multi-worker
